---
name: File-AptFetch
version: 0.0.7
author:
  - 'Eric Pozharski <whynot@cpan.org>'
abstract: perl interface onto APT-Methods.
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  IO::Pipe: ''
  perl: !!perl/hash:version
    original: v5.6
    qv: 1
    version:
      - 5
      - 6
      - 0
build_requires:
  Test::More: ''
provides:
  File::AptFetch:
    file: lib/File/AptFetch.pm
    version: 0.0.7
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
