---
name: File-AptFetch
version: v0.0.8
author:
  - 'Eric Pozharski <whynot@cpan.org>'
abstract: perl interface onto APT-Methods.
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
build_requires:
  Test::More: ''
requires:
  IO::Pipe: ''
  perl: v5.6.0
configure_requires:
  Module::Build: 0.340201
provides:
  File::AptFetch:
    file: lib/File/AptFetch.pm
    version: v0.0.8
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
