---
abstract: 'perl interface onto APT-Methods'
author:
  - 'Eric Pozharski <whynot@cpan.org>'
build_requires:
  File::Temp: 0
  POSIX: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-AptFetch
provides:
  File::AptFetch:
    file: lib/AptFetch.pm
    version: v0.1.7
  File::AptFetch::Simple:
    file: lib/Simple.pm
    version: v0.1.2
requires:
  perl: v5.8.0
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
version: v0.1.7
