#!/usr/bin/perl
# $Id: y-method 350 2009-04-11 18:21:15Z whynot $

use strict;
use warnings;

package main;
our $VERSION = q|0.0.4|;

use IO::Handle;

STDOUT->autoflush(1);

my $fn = <DATA>;
chomp $fn;
open STDERR, q|>|, $fn or
  die qq|open (STDERR) failed: $!|;

while(<DATA>)             {
    chomp;
    print STDERR qq|[$_]\n|;
    print STDOUT qq|$_\n|; };

# vim: set filetype=perl

